### ISSUE TITLE
Autoscaling fails to scale node pool when variable `min_nodes` is set to `0`

### ISSUE THREAD

**Issue by thpang** [sassoftware/viya4-iac-aws#77]
### Terraform Version

```bash
{
  "terraform_version": "\"1.0.0\"",
  "terraform_revision": "null",
  "terraform_outdated": "true",
  "provider_selections": "{\"registry.terraform.io/hashicorp/aws\":\"3.43.0\",\"registry.terraform.io/hashicorp/cloudinit\":\"2.2.0\",\"registry.terraform.io/hashicorp/external\":\"2.1.0\",\"registry.terraform.io/hashicorp/kubernetes\":\"2.2.0\",\"registry.terraform.io/hashicorp/local\":\"2.1.0\",\"registry.terraform.io/hashicorp/null\":\"3.1.0\",\"registry.terraform.io/hashicorp/random\":\"3.1.0\",\"registry.terraform.io/hashicorp/template\":\"2.2.0\",\"registry.terraform.io/terraform-aws-modules/http\":\"2.4.1\"}"
}
```

### Terraform Variable File

```terraform
## Cluster Node Pools config - minimal
cluster_node_pool_mode   = "minimal"
node_pools = {
  cas = {
    "vm_type"            = "r5.xlarge"
    "os_disk_type"       = "gp2"
    "os_disk_size"       = 200
    "os_disk_iops"       = 0
    "min_nodes"          = 0  ## BUG - Having this value set forces the desired node count to 0 as well.
    "max_nodes"          = 5
    "node_taints"        = ["workload.sas.com/class=cas:NoSchedule"]
    "node_labels" = { 
      "workload.sas.com/class" = "cas" 
    }
    "custom_data" = ""
    "metadata_http_endpoint"               = "enabled"
    "metadata_http_tokens"                 = "required"
    "metadata_http_put_response_hop_limit" = 1
  },
  generic = {
    "vm_type"            = "m5.2xlarge"
    "os_disk_type"       = "gp2"
    "os_disk_size"       = 200
    "os_disk_iops"       = 0
    "min_nodes"          = 0  ## BUG - Having this value set forces the desired node count to 0 as well.
    "max_nodes"          = 5
    "node_taints"        = []
    "node_labels" = {
      "workload.sas.com/class"        = "compute"
      "launcher.sas.com/prepullImage" = "sas-programming-environment"
    }
    "custom_data" = ""
    "metadata_http_endpoint"               = "enabled"
    "metadata_http_tokens"                 = "required"
    "metadata_http_put_response_hop_limit" = 1
  }
}
```

### Steps to Reproduce

Using the `sample-input-minimal.tfvars` file or any `.tfvars` file that has the `min_nodes` values set to 0 (zero) will
cause this issue. 

In order to create a cluster that can fully `autoscale` in AWS you'll also need to run `baseline,install` with the Viya 4 Deployment repo located [here](https://github.com/sassoftware/viya4-deployment).

### Expected Behavior

Once the cluster has been setup one should be able to apply pods with the appropriate `tolerations` and `affinity` values 
into the cluster which would then spin up nodes in the appropriate node pools. By applying the following 2 pods both the `cas` and `generic` node pools should add at least 1 node to the cluster for use.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-tol-na-cas
  labels:
    app: ubuntu
  namespace: default
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "0.5"
        memory: "128Mi"
      limits:
        cpu: "1.0"
        memory: "512Mi"
  restartPolicy: Always
  tolerations:
  - key: "workload.sas.com/class"
    value: "cas"
    operator: "Equal"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: workload.sas.com/class
              operator: In
              values:
              - cas
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-na-generic
  labels:
    app: ubuntu
  namespace: default
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "0.5"
        memory: "128Mi"
      limits:
        cpu: "1.0"
        memory: "512Mi"
  restartPolicy: Always
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: workload.sas.com/class
              operator: In
              values:
              - compute
```

### Actual Behavior

Applying the above pods into the cluster does nothing. If you view the log from the autoscaler pod in the cluster it finds no nodes it can use. This leaves the pods unable to actually run in the cluster.
